#!/bin/sh

../tr.init

T="../../src/gate/rfc2ftn -c../cf/fidogate.conf -vvvvvvv -i"
TC="../../src/gate/rfc2ftn -cconfig -vvvvvvv -i"

echo "tc: running"

##### NetMail #####
$T test@f123.n2499.z2.fidonet.org <<EOF
Subject: Test tc.gate7 / 00000001
From: abc@fido.de

TEST ;-)
EOF

$T test_user@f123.n2499.z2.fidonet.org <<EOF
Subject: Test tc.gate7 / 00000002
From: abc@fido.de

TEST ;-)
EOF

$T test.user@f123.n2499.z2.fidonet.org <<EOF
Subject: Test tc.gate7 / 00000003
From: abc@fido.de

TEST ;-)
EOF


$T test_user@abc.def.org <<EOF
Subject: Test tc.gate7 / no output
From: abc@fido.de

TEST ;-)
EOF

$T test_user@f123.n2499.z2.fidonet.org <<EOF
Subject: Test tc.gate7 / 00000004
From: abc@fido.de (Test User)

TEST ;-)
EOF

$T test_user@f123.n2499.z2.fidonet.org <<EOF
Subject: Test tc.gate7 / 00000005
From: abc@fido.de (_Test_ _User_)

TEST ;-)
EOF

$T test_user@f123.n2499.z2.fidonet.org <<EOF
Subject: Test tc.gate7 / 00000006
From: abc@fido.de (Test.User)

TEST ;-)
EOF

$T test_user@f123.n2499.z2.fidonet.org <<EOF
Subject: Test tc.gate7 / 00000007
From: abc@f678.n9999.z242.fido.de (Test User)

TEST ;-)
EOF

$T test_user@f123.n2499.z2.fidonet.org <<EOF
Subject: Test tc.gate7 / 00000008
From: abc@fido.de (Test User)
Reply-To: abc@f678.n9999.z242.fido.de (Test User)

TEST ;-)
EOF

$T test_user@f123.n2499.z2.fidonet.org <<EOF
Subject: Test tc.gate7 / 00000009
From: abc@fido.de (Test User X)
Reply-To: test_user@f678.n9999.z242.fido.de

TEST ;-)
EOF

$T test_user@f123.n2499.z2.fidonet.org <<EOF
Subject: Test tc.gate7 / 00000010
From: abc@fido.de (Test User X)
Reply-To: abc@f678.n9999.z242.fido.de

TEST ;-)
EOF

$T test_user@f123.n2499.z2.fidonet.org <<EOF
Subject: Test tc.gate7 / 00000011
From: abc@f678.n9999.z242.fido.de (Test User X)
Reply-To: abc@f678.n9999.z242.fido.de

TEST ;-)
EOF


##### EchoMail #####

$T -n <<EOF
Newsgroups: test
Subject: Test tc.gate7 / 00000012
From: abc@f678.n9999.z242.fido.de (Test User X)
X-Comment-To: test_user@f123.n2499.z2.fidonet.org

TEST ;-)
EOF

$T -n <<EOF
Newsgroups: test
Subject: Test tc.gate7 / 00000013
From: abc@f678.n9999.z242.fido.de (Test User X)
X-Comment-To: test_user

TEST ;-)
EOF

$T -n <<EOF
Newsgroups: test
Subject: Test tc.gate7 / 00000014
From: abc@f678.n9999.z242.fido.de (Test User X)
Reply-To: abc@f678.n9999.z242.fido.de
X-Comment-To: Hans Test User

TEST ;-)
EOF

$T -n <<EOF
Newsgroups: test
Subject: Test tc.gate7 / 00000015
From: abc@f678.n9999.z242.fido.de (Test User X)
Reply-To: abc@f678.n9999.z242.fido.de
X-Comment-To: test@p1.f2.n3.z4.fidonet.org (Hans Test User)

TEST ;-)
EOF

$T -n <<EOF
Newsgroups: test
Subject: Test tc.gate7 / 00000016
From: abc@f678.n9999.z242.fido.de (Test User X)
X-Comment-To: (Test User X)

TEST ;-)
EOF


##### MIME #####

$T test_user@f123.n2499.z2.fidonet.org <<EOF
Subject: Test tc.gate7 / 00000017
From: kris@schulung.netuse.de (Kristian =?ISO-8859-1?Q?K=F6hntopp?= )

TEST ;-)
EOF

$T test_user@f123.n2499.z2.fidonet.org <<EOF
Subject: Test tc.gate7 / 00000018
From: kris@schulung.netuse.de (=?ISO-8859-1?Q?Kristian K=F6hntopp?=)

TEST ;-)
EOF

$T test_user@f123.n2499.z2.fidonet.org <<EOF
Date: Sun, 17 Aug 1997 13:56:56 +0200 (MET DST)
From: Martin Junius <mj@orodruin.fido.de>
To: Martin Junius <mj@orodruin.fido.de>
Subject: Test tc.gate7 / 00000019: =?iso-8859-1?Q?Umlaute_=F6=E4=FC=DF=D6=C4=DC_im_Subject?=
Message-ID: <Pine.LNX.3.95.970817135631.1113F-100000@orodruin.fido.de>
MIME-Version: 1.0
Content-Type: TEXT/PLAIN; charset=iso-8859-1
Content-Transfer-Encoding: 8bit

TEST

öäüßÖÄÜ
EOF



##### Mit Gateway 242:4900/99 ################################################

##### EchoMail #####

$TC -n <<EOF
Newsgroups: test
Subject: Test tc.gate7 / 00000020
From: abc@f678.n9999.z242.fido.de (Test User X)
X-Comment-To: test_user@f123.n2499.z2.fidonet.org

TEST ;-)

From: abc@f678.n9999.z242.fido.de (Test User X)
X-Comment-To: test_user@f123.n2499.z2.fidonet.org
EOF

$TC -n <<EOF
Newsgroups: test
Subject: Test tc.gate7 / 00000021
From: abc@f678.n9999.z242.fido.de (Test User X)
X-Comment-To: test_user

TEST ;-)

From: abc@f678.n9999.z242.fido.de (Test User X)
X-Comment-To: test_user
EOF

$TC -n <<EOF
Newsgroups: test
Subject: Test tc.gate7 / 00000022
From: abc@f678.n9999.z242.fido.de (Test User X)
Reply-To: abc@f678.n9999.z242.fido.de
X-Comment-To: Hans Test User

TEST ;-)

From: abc@f678.n9999.z242.fido.de (Test User X)
Reply-To: abc@f678.n9999.z242.fido.de
X-Comment-To: Hans Test User
EOF

$TC -n <<EOF
Newsgroups: test
Subject: Test tc.gate7 / 00000023
From: abc@f678.n9999.z242.fido.de (Test User X)
Reply-To: abc@f678.n9999.z242.fido.de
X-Comment-To: test@p1.f2.n3.z4.fidonet.org (Hans Test User)

TEST ;-)

From: abc@f678.n9999.z242.fido.de (Test User X)
Reply-To: abc@f678.n9999.z242.fido.de
X-Comment-To: test@p1.f2.n3.z4.fidonet.org (Hans Test User)
EOF

$TC -n <<EOF
Newsgroups: test
Subject: Test tc.gate7 / 00000024
From: abc@f678.n9999.z242.fido.de (Test User X)
X-Comment-To: (Test User X)

TEST ;-)

From: abc@f678.n9999.z242.fido.de (Test User X)
X-Comment-To: (Test User X)
EOF
