#!/bin/sh

../tr.init

echo "tc: copying input packets"
cp ../ti.pkt-misc/t-fattach.pkt pin
cp ../ti.pkt-misc/testfile.zip  pin

echo "tc: running"
../../src/toss/ftntoss  -c../cf/fidogate.conf -vv
../../src/toss/ftnroute -c../cf/fidogate.conf -vv
../../src/toss/ftnpack  -c../cf/fidogate.conf -vv -Fpin

echo "tc: copying input packets"
rm pin/*
cp ../ti.pkt-misc/t-fattach.pkt pin
cp ../ti.pkt-misc/testfile.zip  pin/TestFile.ZIP

echo "tc: running"
../../src/toss/ftntoss  -c../cf/fidogate.conf -vv
../../src/toss/ftnroute -c../cf/fidogate.conf -vv
../../src/toss/ftnpack  -c../cf/fidogate.conf -vvvv -Fpin
