#!/bin/sh

echo "tc: clean-up"
./clean

echo "tc: init"
mkdir toss toss/in toss/tmp toss/out toss/pack bt
mkdir seq

echo "tc: copying input packets"
cp ../ti.pkt-misc/t-fattach.pkt toss/in
cp ../ti.pkt-misc/testfile.zip  toss/in

echo "tc: running"
../../src/toss/ftntoss  -L../cf -S. -vv
../../src/toss/ftnroute -L../cf -S. -vv
../../src/toss/ftnpack  -L../cf -S. -B./bt -vv -Ftoss/in

echo "tc: copying input packets"
rm toss/in/*
cp ../ti.pkt-misc/t-fattach.pkt toss/in
cp ../ti.pkt-misc/testfile.zip  toss/in/TestFile.ZIP

echo "tc: running"
../../src/toss/ftntoss  -L../cf -S. -vv
../../src/toss/ftnroute -L../cf -S. -vv
../../src/toss/ftnpack  -L../cf -S. -B./bt -vvvv -Ftoss/in
