#!/bin/sh

../tr.init

R="../../src/gate/rfc2ftn -c../cf/fidogate.conf -vvvvvvv"
R1="../../src/gate/rfc2ftn -cconfig -vvvvvvv"
R2="../../src/gate/rfc2ftn -cconfig2 -vvvvvvv"
F="../../src/gate/ftn2rfc -c../cf/fidogate.conf -vvvvvvv"

echo "tc: running"

# Test with local config
echo " "
echo "----- rfc2ftn: mail to mj@orodruin.fido.de -----"
$R1 mj@orodruin.fido.de <<EOF
Subject: Mail -> mj
From: Test User <test@blah.org>

TEST - OK
EOF
ex=$?
echo "Exit=$ex"

echo " "
echo "----- rfc2ftn: mail to Martin_Junius@orodruin.fido.de -----"
$R1 Martin_Junius@orodruin.fido.de <<EOF
Subject: Mail -> Martin_Junius
From: Test User <test@blah.org>

TEST - OK
EOF
ex=$?
echo "Exit=$ex"

echo " "
echo "----- rfc2ftn: mail to postmaster@orodruin.fido.de -----"
$R1 postmaster@orodruin.fido.de <<EOF
Subject: Mail -> postmaster
From: Test User <test@blah.org>

TEST - OK
EOF
ex=$?
echo "Exit=$ex"

echo " "
echo "----- rfc2ftn: mail to unknown@orodruin.fido.de -----"
$R1 unknown@orodruin.fido.de <<EOF
Subject: Mail -> unknown
From: Test User <test@blah.org>

TEST - BOUNCE
EOF
ex=$?
echo "Exit=$ex"

echo " "
echo "----- rfc2ftn: mail to Max_Tester@orodruin.fido.de -----"
$R1 Max_Tester@orodruin.fido.de <<EOF
Subject: Mail -> unknown
From: Test User <test@blah.org>

TEST - OK
EOF
ex=$?
echo "Exit=$ex"

echo " "
echo "----- rfc2ftn: mail to Tester@orodruin.fido.de -----"
$R1 Tester@orodruin.fido.de <<EOF
Subject: Mail -> unknown
From: Test User <test@blah.org>

TEST - OK
EOF
ex=$?
echo "Exit=$ex"

echo " "
echo "----- rfc2ftn: mail to max_tester@orodruin.fido.de -----"
$R1 max_tester@orodruin.fido.de <<EOF
Subject: Mail -> unknown
From: Test User <test@blah.org>

TEST - OK
EOF
ex=$?
echo "Exit=$ex"

echo " "
echo "----- rfc2ftn: mail to tester@orodruin. fido.de -----"
$R1 tester@orodruin.fido.de <<EOF
Subject: Mail -> unknown
From: Test User <test@blah.org>

TEST - OK
EOF
ex=$?
echo "Exit=$ex"


# Generate mail addressed to Test 1/Test 2
echo "----- rfc2ftn: mail to test_1 @ 2:2/0.0 -----"
$R -i test_1@p0.f0.n2.z2 <<EOF
Subject: Mail -> Test 1
From: Test User <test@blah.org>

TEST
EOF

echo "----- rfc2ftn: mail to test_2 @ 2:2/0.0 -----"
$R -i test_2@p0.f0.n2.z2 <<EOF
Subject: Mail -> Test 2
From: Test User <test@blah.org>

TEST
EOF

# Move to SPOOLDIR/in and run ftn2rfc
echo ""
echo "----- ftn2rfc -----"
mv ./outpkt/mail/*.pkt ./pin
$F
