#!/bin/sh

../tr.init

A="../../src/areafix/ftnafutil -c../cf/fidogate.conf -vvv"
D="../../src/util/pktdebug"

cp areas.bbs tmp_areas.bbs

echo "--------- ftnafutil DELETE ----------"
$A -b tmp_areas.bbs   DELETE
echo "--------- ftnafutil SUBSCRIBE ----------"
$A -b tmp_areas.bbs   SUBSCRIBE
echo "--------- ftnafutil UNSUBSCRIBE ----------"
$A -b tmp_areas.bbs   UNSUBSCRIBE

echo "--------- packets ----------"
$D -t outpkt/*.pkt
