#!/bin/sh

../tr.init

A="../../src/areafix/ftnafutil -c../cf/toss.conf -vvv"


cp areas.bbs tmp_areas.bbs

$A -b tmp_areas.bbs   DELETE
$A -b tmp_areas.bbs   SUBSCRIBE
$A -b tmp_areas.bbs   UNSUBSCRIBE
