#!/bin/sh
#
# $Id: ffxmail,v 1.2 1998/02/01 18:51:25 mj Exp $
#
# Test ffxmail
#

if [ $# -lt 2 ] ;then
	echo "usage: ffxmail Z:N/F.P|HOST user@domain ..."
	exit 1
fi

node="$1"
shift
addr="$*"

nocmpr="-n";

case $node in

    test)
	batch="-b test"
	faddr="242:1/1"
	;;

    # Unknown node
    *)
	echo "ffxmail: unknown node $node"
	# EX_NOHOST
	exit 68
	;;

esac

exec ../../src/ffx/ffx -c../cf/ffx.conf -vvv $nocmpr $batch -- $faddr rmail $addr
