#!/bin/sh

../tr.init

F="./ffxmail"
P="../../src/toss/ftnpack -c../cf/fidogate.conf -vvv"
X="../../src/ffx/ffxqt -c../cf/fidogate.conf -vvv"

echo "tc: running"

# Some test ffxmail
$F test 123@fido.de <<EOF
Subject: Test
From: mj@fido.de
To: mj@fido.de

----
TEST
----
EOF

$F test abc@fido.de <<EOF
Subject: Test
From: mj@fido.de
To: mj@fido.de

----
TEST
----
EOF

$F test def@fido.de <<EOF
Subject: Test
From: mj@fido.de
To: mj@fido.de

----
TEST
----
EOF

$F test ghi@fido.de <<EOF
Subject: Test
From: mj@fido.de
To: mj@fido.de

----
TEST
----
EOF

# Ouput
ls bt/out.0f2/test
cat -v bt/out.0f2/test/*
cp bt/out.0f2/test/* pin

# Pack it
$P -f 242:1/1 -I %B/out.0f2/test

# Run ffxqt
FIDOGATE_LOGFILE=`pwd`/log
FIDOGATE_SPOOLDIR=`pwd`
FIDOGATE_VARDIR=`pwd`
FIDOGATE_LOCKDIR=`pwd`/locks
export FIDOGATE_LOGFILE FIDOGATE_SPOOLDIR FIDOGATE_VARDIR FIDOGATE_LOCKDIR
$X -t
