#!/bin/sh

../tr.init

F="../../src/gate/ftn2rfc -v -c./config"
R="../../src/gate/rfc2ftn -v -c./config"

echo "tc: copying input packets"
cp ../ti.pkt-z2/*.[pP][kK][tT] pin

echo "tc: running ftn2rfc"
$F

echo "tc: running rfc2ftn"
for f in outrfc/news/*.rfc; do
    $R -b -n < $f;
done
