#!/bin/sh

../tr.init

G="../../src/gate/rfc2ftn  -v -i -cfidogate.conf"
T="../../src/toss/ftntoss  -v    -cfidogate.conf"
R="../../src/toss/ftnroute -v    -cfidogate.conf"
P="../../src/toss/ftnpack  -v    -cfidogate.conf"

# create messages

#$G -a 2:2449/417.2 Test_User@2:2449/123.4 <<EOF
$G -a p2.f417.n2449.z2 Test_User@2:2449/123.4 <<EOF
To: test (Test User)
From: mj@fido.de (Martin Junius)
Subject: Test Point 1

TEST
EOF

#$G -a 2:2449/450.1 Test_User@2:2449/567.8 <<EOF
$G -a p1.f450.n2449.z2 Test_User@2:2449/567.8 <<EOF
To: test (Test User)
From: mj@fido.de (Martin Junius)
Subject: Test Point 1

TEST
EOF

$G -n <<EOF
Newsgroups: abc
X-Comment-To: test (Test User)
From: mj@fido.de (Martin Junius)
Subject: Test Area ABC

TEST
EOF

$G -n <<EOF
Newsgroups: def
X-Comment-To: test (Test User)
From: mj@fido.de (Martin Junius)
Subject: Test Area DEF

TEST
EOF


# toss messages
cp outpkt/*/*.pkt pin

$T -t -p
$R
#$P
