#!/bin/sh

../tr.init

./run1-1 &
./run1-1 &
./run1-1 &
./run1-1 &

echo "---- Press RETURN to stop ----"
read xx

for f in locks/test.R*; do
    if [ -f $f ]; then
	pid=`echo $f | sed -e 's/^.*test\..//'`
	kill $pid
	echo "kill $pid"
    fi
done

for f in locks/test.L*; do
    if [ -f $f ]; then
	pid=`echo $f | sed -e 's/^.*test\..//'`
	kill $pid
	echo "kill $pid"
    fi
done

rm -f locks/*
