#!/bin/sh

NODE=2:123/456

L="../../src/util/ftnbsy -c../cf/toss.conf -v"

echo "$$" > locks/test.R$$

T=`expr $$ % 10`
T=`expr $T + 1`

echo "tc.lock $$ $NODE: loop $T s"

while true; do
    # lock
    echo "tc.lock $$ $NODE: locking"
    $L -w -l $NODE
    if [ $? -ne 0 ]; then
	echo "tc.lock $$: lock failed, exiting"
	exit 1
    fi
    echo "tc.lock $$ $NODE: locked"

    sleep $T

    # unlock
    $L -u $NODE
    echo "tc.lock $$ $NODE: unlocked"

    sleep $T
done

exit 0

