#!/bin/sh

echo "tc: clean-up"
./clean

echo "tc: init"
mkdir toss toss/in toss/tmp toss/out toss/pack toss/bad bt
mkdir seq
:> history
:> history.dir
:> history.pag

echo "tc: copying input packets"
cp ../ti.pkt-z2/* toss/in

echo "tc: running"
../../src/toss/ftntoss  -L../cf -S. -vv

echo "tc: copying input packets"
cp ../ti.pkt-z2/* toss/in

echo "tc: running"
../../src/toss/ftntoss  -L../cf -S. -vv

echo "tc: sleeping for 20 s"
sleep 20

echo "tc: copying input packets"
cp ../ti.pkt-misc/t-nomsgid.pkt toss/in

echo "tc: running"
../../src/toss/ftntoss  -L../cf -S. -vv

echo "tc: running expire"
# 0.0002 days ~ 17 sec
cp history history.save
../../src/toss/ftnexpire -L../cf -S. -vvvvvvv -m 0.0002

echo "tc: copying input packets"
cp ../ti.pkt-misc/t-nomsgid.pkt toss/in

echo "tc: running"
../../src/toss/ftntoss  -L../cf -S. -vv

