#!/bin/sh

FIDOGATE_CONFIGDIR=../cf
export FIDOGATE_CONFIGDIR

../tr.init

T1="../../src/gate/rfc2ftn -vvvvv"
T2="../../src/gate/ftn2rfc -vvvvv"

echo "tc: running"

$T1 Martin_Junius@f110.n2452.z2.fidonet.org <body1
$T1 Martin_Junius@f110.n2452.z2.fidonet.org <body2

cp ../ti.8bit/*.pkt pin
$T2 -c config1
cp ../ti.8bit/*.pkt pin
$T2 -c config2
cp ../ti.8bit/*.pkt pin
$T2 -c config3
