#!/bin/sh

#
# Test with large news articles (>16K)
#
../tr.init

T="../../src/gate/rfc2ftn -vvvvv"

echo "tc: running"

for f in ../ti.news-l/[0-9]*; do
  echo "News article file $f"
  $T -c../cf/fidogate.conf -n <$f
  $T -cconfig -n <$f
  $T -cconfig2 -n <$f
done

for f in ../ti.mail-l/[0-9]*; do
  echo "Mail message file $f"
  $T -c../cf/fidogate.conf test@hippo.fido.de <$f
  $T -cconfig test@hippo.fido.de <$f
  $T -cconfig3 test@hippo.fido.de <$f
done

# last test returns with error status
exit 0
