#!/bin/sh

../tr.init

echo "tc: copying input packets"
cp ../ti.pkt-misc/t-bad.pkt pin

echo "tc: running"
../../src/toss/ftntoss  -c../cf/fidogate.conf -vv -bareas1.bbs

echo "tc: copying input packets"
cp ../ti.pkt-misc/t-bad.pkt pin

echo "tc: running"
../../src/toss/ftntoss  -c../cf/fidogate.conf -vv -bareas2.bbs

echo "tc: copying input packets"
cp ../ti.pkt-misc/t-bad.pkt pin

echo "tc: running"
../../src/toss/ftntoss  -c../cf/fidogate.conf -vv -a 2:2452/151 -bareas1.bbs
