#!/bin/sh

../tr.init

echo "tc: copying input packets"
cp ../ti.pkt-misc/t-bad.pkt toss/in

echo "tc: running"
../../src/toss/ftntoss  -L../cf -S. -vv -bareas1.bbs

echo "tc: copying input packets"
cp ../ti.pkt-misc/t-bad.pkt toss/in

echo "tc: running"
../../src/toss/ftntoss  -L../cf -S. -vv -bareas2.bbs

echo "tc: copying input packets"
cp ../ti.pkt-misc/t-bad.pkt toss/in

echo "tc: running"
../../src/toss/ftntoss  -L../cf -S. -vv -a 2:2452/151 -bareas1.bbs
