#!/bin/sh

T=../../src/common/testparse

echo "tc: running testparse"

$T '1:2/3.4'
$T '1:2/3'
$T '1:2/255'
$T '1:2'
$T '2/3.4'
$T '3.4'
$T '3'
$T '*'
$T 'all'
$T 'World'
$T '*:*'
$T '*:*/*'
$T 'all:*/*.all'
$T '1:2/3.*'
$T '1:2/*'
$T '1:*'
$T '1:*/3'
$T '1:*/4.255'
