#!/bin/sh

../tr.init

U="../../src/toss/rununpack -v -c../cf/fidogate.conf"
T="../../src/toss/runtoss   -v -c../cf/fidogate.conf"

zip -k9j abcd1234.mo0 ../ti.pkt-z2/*.PKT
arc a    abcd1234.tu1 ../ti.pkt-z2/*.PKT
lha ai   abcd1234.we2 ../ti.pkt-z2/*.PKT
# broken lha
mv       abcd1234.lzh abcd1234.we2
# unknown archive
echo "--TEST--" >abcd1234.th9
# partial archive
head -c 40 abcd1234.mo0 >abcd1234.fr9

mv abcd1234.* pin

FIDOGATE_LOGFILE=`pwd`/log
export FIDOGATE_LOGFILE

$U `pwd`/pin
$T `pwd`/pin
