#!/bin/sh

../tr.init

T="../../src/toss/ftnaf -L../cf -S."

echo "tc: running"

# command line
$T -v -b areas.bbs 2:2452/110.90 query
$T -v -b areas.bbs 2:2452/110.90 list
$T -v -b areas.bbs 2:2452/110.90 listall

cp areas.bbs tmp_areas.bbs

$T -v -b tmp_areas.bbs 2:2452/110.1 add linux.ger
$T -v -b tmp_areas.bbs 2:2452/110.1 add tolkien.ger
$T -v -b tmp_areas.bbs 2:2452/110.1 add xx
$T -v -b tmp_areas.bbs 2:2452/110.1 add yy
$T -v -b tmp_areas.bbs 99:2452/110.1 add zz

$T -v -b tmp_areas.bbs 2:2452/110.1 add UNKNOWN.GER
#$T -v -b tmp_areas.bbs -x./unknown 2:2452/110.1 add UNKNOWN.GER

$T -v -b tmp_areas.bbs 2:99/99 del test1
$T -v -b tmp_areas.bbs 2:99/99 del test2
$T -v -b tmp_areas.bbs 2:99/99 del test2


# mail interface
$T -m -r -n -v -b tmp_areas.bbs <<EOF
From: Sysop@f5678.n1234.z2.fidonet.org
Subject: WUSEL

add *.GER
add TEST1
add TEST2
list
query
unlinked
EOF

$T -m -r -n -v -b tmp_areas.bbs <<EOF
From: Sysop@f5678.n1234.z2.fidonet.org
X-FTN-From: Sysop @ 2:1234/5678
Subject: WUSEL

-TEST1
-TEST2
EOF

$T -m -r -n -v -b tmp_areas.bbs <<EOF
From: mj@fido.de
Subject: Areafix request

add *.GER
EOF

$T -m -r -n -v -b tmp_areas.bbs <<EOF
From: mj@fido.de
Subject: Areafix request

password 2:1234/5678 WUSEL
add *.GER
list
EOF
