#!/bin/sh

../tr.init

T="../../src/areafix/ftnaf -vvv -cconfig"

echo "tc: running"

# command line
echo "----- Testing command line -----"

$T -b areas.bbs -- 2:2452/110.90 query
$T -b areas.bbs -- 2:2452/110.90 list
$T -b areas.bbs -- 2:2452/110.90 listall

cp areas.bbs tmp_areas.bbs

$T -b tmp_areas.bbs -- 2:2452/110.1 sub linux.ger
$T -b tmp_areas.bbs -- 2:2452/110.1 +tolkien.ger
$T -b tmp_areas.bbs -- 2:2452/110.1 subscribe xx
$T -b tmp_areas.bbs -- 2:2452/110.1 +yy
$T -b tmp_areas.bbs -- 99:2452/110.1 +zz

$T -b tmp_areas.bbs -- 2:2452/110.1 UNKNOWN.GER
#$T -b tmp_areas.bbs -x./unknown 2:2452/110.1 sub UNKNOWN.GER

$T -b tmp_areas.bbs -- 2:99/99 unsub test1
$T -b tmp_areas.bbs -- 2:99/99 -test2
$T -b tmp_areas.bbs -- 2:99/99 unsubscribe test2

$T -b tmp_areas.bbs -- 2:99/99 new LINUX.GER
$T -b tmp_areas.bbs -- 2:99/99 new LINUX.GER -#
$T -b tmp_areas.bbs -- 2:99/99 new AREA.NEW -d New-Test-Area
$T -b tmp_areas.bbs -- 2:99/99 new AREA.NEW -#
$T -b tmp_areas.bbs -- 2:99/99 new AREA.NEW1 -p -r
$T -b tmp_areas.bbs -- 2:99/99 new AREA.NEWER -p -l 10
$T -b tmp_areas.bbs -- 2:99/99 new AREA.NEWEST -l 5 -k abcxyz

echo " "

# mail interface
echo "----- Testing mail interface -----"

$T -m -n -b tmp_areas.bbs <<EOF
From: Sysop@f5678.n1234.z2.fidonet.org
Subject: WUSEL

%+*.GER
%+TEST1
%+TEST2
%list
%query
%unlinked
%new NEW
EOF

$T -m -n -b tmp_areas.bbs <<EOF
From: Sysop@test.fidonet.org
X-FTN-From: Sysop Mueller @ 2:1234/5678
Subject: WUSEL

vacation *.ger
-TEST1
-TEST2
&NEW
~XX
EOF

$T -m -n -b tmp_areas.bbs <<EOF
From: mj@fido.de
Subject: Areafix request

+*.GER
EOF

$T -m -n -b tmp_areas.bbs <<EOF
From: mj@fido.de
Subject: Areafix request

from 2:1234/5678 WUSEL
+*.GER
list
EOF

$T -m -n -b tmp_areas.bbs <<EOF
From: mj@fido.de
Subject: Areafix request

from 2:1/1 DUDEL
&NEW_AREA_TEST -z 99 -l 99 -k abcdefghijklmnopqrstuvwxyz
~XX
~xxxxxxxxxx
listall
EOF

# No mailer, stdout
$T -m -r -n -b tmp_areas.bbs <<EOF
From: mj@fido.de
Subject: Areafix request

help
EOF
