#!/bin/sh

../tr.init

T1="../../src/util/ftnfattach -c./tmp_config.dos -v"
T2="../../src/common/testflo  -c./tmp_config.dos -vvvvv"
T3="../../src/util/ftnflo     -c./tmp_config.dos"
A="1:2/3.4"

cp config.dos tmp_config.dos
echo "DosDrive X: "`pwd` >>tmp_config.dos
cp config.dos tmp_file1.txt
cp config.dos tmp_file2.xyz
cp run        tmp_file3.abc

echo "tc: running"
$T1 $A `pwd`/tmp_file1.txt
$T1 $A `pwd`/tmp_file2.xyz
$T1 $A `pwd`/tmp_file3.abc
$T1 $A \#`pwd`/tmp_file1.txt
$T1 $A `pwd`/tmp_file2.xyz
$T1 $A \^`pwd`/tmp_file3.abc

$T2 $A

$T1 $A `pwd`/tmp_file1.txt
$T1 $A `pwd`/tmp_file2.xyz
$T1 $A `pwd`/tmp_file3.abc
$T1 $A \#`pwd`/tmp_file1.txt
$T1 $A `pwd`/tmp_file2.xyz
$T1 $A \^`pwd`/tmp_file3.abc

$T3 -l $A
$T3 -vvvvv -x 'echo --- %s ---' $A
