#!/bin/sh

../tr.init

T="../../src/gate/rfc2ftn -c../cf/fidogate.conf -v"
T2="../../src/gate/rfc2ftn -cconfig2 -v"

echo "tc: running"

##### Test rfc2ftn bounce #####

# Down
$T test@spam.fido.de <<EOF
Subject: Test --------
From: abc@blubber.fasel.org
Message-ID: <Test--------@x.y.z>

TEST ;-)
EOF
echo " "

# Unknown
$T test@unknown.fido.de <<EOF
Subject: Test --------
From: abc@blubber.fasel.org
Message-ID: <Test--------@x.y.z>

TEST ;-)
EOF
echo " "

# Not registered
$T test@p2.f2.n2.z2.fido.de <<EOF
Subject: Test --------
From: abc@blubber.fasel.org
Message-ID: <Test--------@x.y.z>

TEST ;-)
EOF
echo " "

# Zone not supported
$T test@p999.f999.n999.z999.fido.de <<EOF
Subject: Test --------
From: abc@blubber.fasel.org
Message-ID: <Test--------@x.y.z>

TEST ;-)
EOF
echo " "


##### silent #####
echo "----------SILENT----------"

# Unknown
$T2 test@unknown.fido.de <<EOF
Subject: Test --------
From: abc@blubber.fasel.org
Message-ID: <Test--------@x.y.z>

TEST ;-)
EOF
echo " "

exit 0
