#!/bin/sh

../tr.init

G="../../src/gate/rfc2ftn  -v -i -cconfig.gate"
T="../../src/toss/ftntoss  -v -cconfig.main"
R="../../src/toss/ftnroute -v -cconfig.main"
P="../../src/toss/ftnpack  -v -cconfig.main"

# create messages

$G -n <<EOF
Newsgroups: test
Subject: Test Gateway 2:2499/99
From: Test User <test@fido.de>
X-Comment-To: Whole Universe
Message-ID: <test123@fido.de>

Test \
Test - Gateway 2:2499/99
Test /

MfG ... The Test User ;-)
EOF

# toss messages
$T -Ioutpkt/news -b./areas.bbs
$R 
#$P
