#!/bin/sh
#
# $Id: mkmaildb,v 4.3 1996/09/22 20:12:36 mj Exp $
#
# Update db maps in /etc/mail
#
MAILDIR=/etc/mail

if [ -f $MAILDIR/rewrite ] ; then
  makemap hash $MAILDIR/rewrite     < $MAILDIR/rewrite
fi
if [ -f $MAILDIR/mailertable ] ; then
  makemap hash $MAILDIR/mailertable < $MAILDIR/mailertable
fi
