#!/bin/sh
#
# $Id: mkmaildb,v 4.4 1997/10/05 13:43:33 mj Exp $
#
# Update db maps in /etc/mail
#
MAILDIR=/etc/mail

if [ -f $MAILDIR/rewrite ] ; then
  makemap hash $MAILDIR/rewrite     < $MAILDIR/rewrite
fi
if [ -f $MAILDIR/mailertable ] ; then
  makemap hash $MAILDIR/mailertable < $MAILDIR/mailertable
fi
if [ -f $MAILDIR/junk ] ; then
  makemap hash $MAILDIR/junk < $MAILDIR/junk
fi
