#!/bin/sh

../tr.init

T="../../src/gate/rfc2ftn -c../cf/fidogate.conf -vvvvv"
#X="-w normal"
P="-a 2:2452/110.2 -u 2:2452/110.0 $X"
D="../../src/util/pktdebug"

echo "tc: running"

$T $P Martin_Junius@f110.n2452.z2.fidonet.org <body1
$T $P Martin_Junius@f110.n2452.z2.fidonet.org <body2
$T $P Martin_Junius@f110.n2452.z2.fidonet.org <body3
$T $P Martin_Junius@f110.n2452.z2.fidonet.org <body4

$D -t outpkt/*/*.pkt
