#!/bin/sh

../tr.init

R="../../src/gate/rfc2ftn -L../cf -vvv -c./config"
F="../../src/gate/ftn2rfc -L../cf -vvv -c./config"

echo "tc: running"

# Generate mail
$R -a2:2499/99 -u2:2452/110.2 test@2:2452/110.2 <<EOF
Subject: Test bounce: not registered
From: test@f99.n2499.z2.fidonet.org
X-Flags: mn

TEST
EOF

$R -a2:2499/99 -u2:2452/110.2 uucp@2:2452/110.2 <<EOF
Subject: Test bounce: not registered
From: test@f99.n2499.z2.fidonet.org
X-Flags: mn

TEST
EOF

$R -a2:2499/99 -u2:2452/110.2 uucp@2:2452/110.2 <<EOF
Subject: Test bounce: not registered
From: test@f99.n2499.z2.fidonet.org
X-Flags: mn

To: test@blah.blubber.org

TEST
EOF

$R -a2:242/2 -u2:2452/110.2 uucp@2:2452/110.2 <<EOF
Subject: Test bounce: not registered
From: test@f2.n242.z2.fidonet.org
X-Flags: mn

To: test@blah.blubber.org

TEST
EOF

# Move to SPOOLDIR/in and run ftn2rfc
mv out/*.pkt in
$F
