#!/bin/sh

../tr.init

H="../../src/tick/ftnhatch -c../cf/fidogate.conf -vvv"
T="../../src/tick/ftntick  -c../cf/fidogate.conf -vvv"

mkdir tmp_area tmp_unknown

cp testfile.txt tmp_area
echo "testfile.txt  Test file ftnhatch/ftntick" >tmp_area/files.bbs

$H -b fareas.bbs TEST testfile.txt "Test file ftnhatch/ftntick"

mkdir tmp_in tmp_old
cp testfile.txt test1.tic pin
$T -b fareasin.bbs -I ./pin -t

cp testfile.txt test5.tic pin
$T -b fareasin.bbs -I ./pin -t

mv tmp_in/testfile.txt tmp_in/testold.txt
cp testfile.txt test2.tic pin
$T -b fareasin.bbs -I ./pin -t

cp testfile.txt test3.tic pin
$T -b fareasin.bbs -I ./pin -t

cp test4.tic pin
$T -b fareasin.bbs -I ./pin -t

cp testfile.txt test6.tic pin
$T -b fareasin.bbs -I ./pin -t
