#!/bin/sh

../tr.init

T="../../src/gate/rfc2ftn -c../cf/fidogate.conf -v"

echo "tc: running"
for f in ../ti.news-a/[0-9]*; do
  echo "News article file $f"
  $T -vvvvvv -n <$f
done

../../src/util/pktdebug -t outpkt/*/*.pkt
