#!/usr/bin/perl

require "getopts.pl";
&Getopts('n:q');

$n = $opt_n ? $opt_n : 1;


srand(time ^ $$);

@d1 = ("de", "se", "fi", "fr", "uk", "com", "edu", "mil", "net" );
@d2 = ("abc", "def", "ghi", "jkl", "mno", "pqr", "stu", "vx", "xyz",
       "blah-stuff", "blubber-long", "marzipan-vendor-site" );
@d3 = ("host", "orc", "test", "ns", "www", "ftp", "orodruin", "morannon" );
@m1 = ("LNX", "Test", "Blah", "Very_Long_Long_Long",
       "abcdefghijklmnopqrstuvwxyz", "A.01121996.140635.00000001" );

@af = ("LINUX.GER", "C_ECHO.GER", "TEX.GER", "UNIX.GER", "TOLKIEN.GER",
       "UNIX", "C_ECHO", "C_PLUSPLUS", "SYSOP", "UNIX", "REGCON.EUR",
       "REGION24", "SYSOP.242", "POINT.242", "ALTIPLEX", "TEST");
@au = ("ALT.FAN.PRATCHETT", "ALT.FAN.DRAGONS", "ALT.TASTELESS",
       "COMP.OS.LINUX", "COMP.SECURITY", "COMP.UNIX", "COMP.EDITORS",
       "COMP.TEXT.TEX", "DE.TEST", "DE.ALT.FAN.N8SCHICHT", "DE.COMM.GATEBAU",
       "DE.COMM.GATEWAYS", "DE.COMP.TEX", "DE.REC.GAMES",
       "REC.ARTS.SF.WRITTEN.ROBERT_JORDAN", "REC.BOOKS.TOLKIEN",
       "NEWS.ANSWERS", "NEWS.ANNOUNCE.IMPORTANT", "GNU.ANNOUNCE",
       "TALK.BIZARRE");

	 
while($n--) {

    $ch = rand(10) % 10;

    if($ch < 6) {
	# Usenet
	$id = sprintf "%s MSGID: <%s.%d.%d@%s.%s.%s> %04x%04x",
	$au[ rand($#au+1) % ($#au+1) ],
	$m1[ rand($#m1+1) % ($#m1+1) ], rand(10000) % 10000, rand(100) % 100,
	$d3[ rand($#d3+1) % ($#d3+1) ], 
	$d2[ rand($#d2+1) % ($#d2+1) ],
	$d1[ rand($#d1+1) % ($#d1+1) ],
	rand(0x10000) % 0x10000, rand(0x10000) % 0x10000;
    } elsif($ch < 8) {
	# Fido
	$id = sprintf "%s MSGID: %d:%d/%d.%d %04x%04x",
	$af[ rand($#af+1) % ($#af+1) ],
	rand(256) % 256 + 1, rand(9999) % 9999 + 1, rand(9999) % 9999 + 1,
	rand(1000) % 1000, rand(0x10000) % 0x10000, rand(0x10000) % 0x10000;
    } else {
	# None
	$id = sprintf "%s NOMSGID: %d:%d/%d.%d %02d%02d%02d %02d%02d%02d %04x%04x",
	$af[ rand($#af+1) % ($#af+1) ],
	rand(256) % 256 + 1, rand(9999) % 9999 + 1, rand(9999) % 9999 + 1,
	rand(1000) % 1000,
	rand(10) % 10 + 90, rand(12) % 12 + 1, rand(31) % 31 + 1,
	rand(24) % 24, rand(60) % 60, rand(60) % 60,
	rand(0x10000) % 0x10000, rand(0x10000) % 0x10000;
    }

    if($opt_q) {
	print "'$id' ";
    } else {
	print "$id\n";
    }

}
