#!/bin/sh

../tr.init

T="../../src/toss/testhistory -c../cf/toss.conf"
# 10 min = -m 0.007
X="../../src/toss/ftnexpire   -c../cf/toss.conf -v -m 0.007"


while true; do
  ./rndmsgid -n 50000 | time -p $T
  $X
done
