#!/bin/sh

../tr.init

T="../../src/toss/testhistory -L../cf -S."
# 10 min = -m 0.007
X="../../src/toss/ftnexpire   -L../cf -S. -v -m 0.007"


echo "Start         150000"
./rndmsgid -n 150000 | time -p $T
echo "     + 25000  175000"
./rndmsgid -n  25000 | time -p $T
echo "     + 25000  200000"
./rndmsgid -n  25000 | time -p $T
echo "     + 25000  225000"
./rndmsgid -n  25000 | time -p $T
echo "     + 25000  250000"
./rndmsgid -n  25000 | time -p $T
echo "     + 25000  275000"
./rndmsgid -n  25000 | time -p $T
echo "     + 25000  300000"
./rndmsgid -n  25000 | time -p $T


