#!/bin/sh

../tr.init

T="../../src/gate/rfc2ftn -L../cf -vvv"

echo "tc: running"

$T Test_user@hippo.fido.de <mail1
$T Test_user@hippo.fido.de <mail2
$T Test_user@hippo.fido.de <mail3
$T Test_user@hippo.fido.de <mail4
