#!/bin/sh

echo "tc: clean-up"
#./clean
:> history
:> history.dir
:> history.pag

#echo "tc: init"
#mkdir in
#mkdir in/mail
#mkdir in/news
#mkdir seq
#
#echo "tc: copying input packets"
#cp ~/*.pkt in

echo "tc: running"
#../../src/gate/ftn2rfc -L../cf -I./in -vv -i
../../src/toss/testhistory -L../cf -vv \
  -vvvvv \
  'MSGID: test1' \
  'NOMSGID: test2' \
  'MSGID: 2:2452/110 abcd1234' \
  'MSGID: 242:1000/123 a1b2c3d4' \
  'some junk'
../../src/toss/testhistory -L../cf -vv \
  -vvvvv \
  'MSGID: test1' \
  'NOMSGID: test2' \
  'MSGID: 2:2452/110 abcd1234' \
  'MSGID: 242:1000/123 a1b2c3d4' \
  'some junk' \


