#!/bin/sh

echo "tc: clean-up"
./clean

echo "tc: init"
mkdir in
mkdir in/mail
mkdir in/news
mkdir seq

echo "tc: copying input packets"
cp ../ti.pkt-z2/* in

echo "tc: running"
../../src/gate/ftn2rfc -L../cf -I./in -v

