#!/bin/sh

../tr.init

echo "tc: copying input packets"
cp ../ti.pkt-z2/*.[pP][kK][tT] in

echo "tc: running (1)"
../../src/gate/ftn2rfc -L../cf -I./in -v

echo "tc: copying input packets"
cp ../ti.pkt-z2/*.[pP][kK][tT] in

echo "tc: running (2)"
../../src/gate/ftn2rfc -L../cf -I./in -cconfig -v


echo "tc: copying input packets"
cp ../ti.pkt-z2/*.[pP][kK][tT] in

echo "tc: running (3)"
../../src/gate/ftn2rfc -L../cf -I./in -1 -v

