#!/bin/sh

../tr.init

T="../../src/gate/ftn2rfc -v"

echo "tc: copying input packets"
cp ../ti.pkt-mail/*.[pP][kK][tT] pin

echo "tc: running"
$T -c../cf/fidogate.conf
cat outrfc/*/*.rfc

echo "tc: copying input packets"
cp ../ti.pkt-mail/*.[pP][kK][tT] pin

echo "tc: running"
$T -cconfig
cat outrfc/*/*.rfc
