#!/bin/sh

../tr.init

A="../../src/areafix/ftnafpkt -c../cf/toss.conf -vvvvvvv"
O="../../src/util/ftnoutpkt -c../cf/toss.conf -vvv"
D="../../src/util/pktdebug -t"

echo "tc: creating Areafix messages"

$O -s WUSEL -f 'Sysop @ 2:1234/5678' 'Areafix @ 2:2499/1' <<EOF
%+*.GER
%+TEST1
%+TEST2
%list
%query
%unlinked
%new NEW
EOF


$O -s WUSEL -f 'Sysop @ 2:1234/5678' 'Areafix @ 2:2499/1' <<EOF
vacation *.ger
-TEST1
-TEST2
EOF


$O -s 'Areafix request' -f 'mj @ 2:2452/110.2' 'Areafix @ 2:2499/1' <<EOF
+*.GER
EOF


$O -s 'Areafix request' -f 'mj @ 2:2452/110.2' 'Areafix @ 2:2499/1' <<EOF
password 2:1234/5678 WUSEL
#*.GER
list
EOF


$O -s 'Areafix request' -f 'Sysop @ 2:2452/110.2' 'Areafix @ 2:2499/1' <<EOF
listall
list
query
unlinked
from     2:1234/5678 WUSEL
passwd   2:1234/5678 WUSEL
password 2:1234/5678 WUSEL
listall
list
query
unlinked
sub *.GER
+TEST1
TEST[1-9]
AB*
unsub DE*
unsubscribe AB*
-*.ger
vacation *.ger
new newarea.ger -z 2 -k test
delete newarea.ger
comment TEST
help
EOF



echo "tc: copying input packets"
mv outpkt/*.pkt pin

cp areas.bbs tmp_areas.bbs

$A -b tmp_areas.bbs -a 2:2499/1

$D outpkt/*.pkt
