#!/bin/sh

../tr.init

V="-vvvvvvv"
A="2:2/2"
AF="2:2/0"
AP="2:2/1"

F1="../../src/util/ftnfattach -c../cf/fidogate.conf $V"
F2="../../src/util/ftnfattach -ctmp_test.conf $V"

O1="../../src/util/ftnoutpkt -c../cf/fidogate.conf -v"
T1="../../src/toss/ftntoss -c../cf/fidogate.conf -v"
R1="../../src/toss/ftnroute -c../cf/fidogate.conf -v"
P1="../../src/toss/ftnpack -c../cf/fidogate.conf $V"


cp test.conf tmp_test.conf
echo "DosDrive X: "`pwd` >>tmp_test.conf
cp run        tmp_file1.txt
cp run        tmp_file2.txt
cp run        tmp_file3.txt

echo "tc: running"

echo "----- Unix config ------------------------------------------------------"
echo "----- file1 -----"
$F1 $A `pwd`/tmp_file1.txt
echo "FLO file:"
cat -v bt/out/*.flo
echo "----- file2 -----"
$F1 $A '#'`pwd`/tmp_file2.txt
echo "FLO file:"
cat -v bt/out/*.flo
echo "----- file3 -----"
$F1 $A '^'`pwd`/tmp_file3.txt
echo "FLO file:"
cat -v bt/out/*.flo

echo "----- file1 again -----"
$F1 $A '#'`pwd`/tmp_file1.txt
echo "FLO file:"
cat -v bt/out/*.flo
echo "----- file2 again -----"
$F1 $A '^'`pwd`/tmp_file2.txt
echo "FLO file:"
cat -v bt/out/*.flo
echo "----- file3 again -----"
$F1 $A `pwd`/tmp_file3.txt
echo "FLO file:"
cat -v bt/out/*.flo

rm -f bt/out/*.flo

echo "----- packet -----"
mkdir tmp_out
$O1 -f "Test@$AF" "Test@$AP" -O./tmp_out <<EOF
Test packet for ftnpack
Test packet for ftnpack
Test packet for ftnpack
Test packet for ftnpack
Test packet for ftnpack
EOF
echo "----- packet toss 1 -----"
cp tmp_out/*.pkt pin
$T1
$R1
$P1
ls bt/out
cat -v bt/out/*.flo
echo "----- packet toss 2 -----"
cp tmp_out/*.pkt pin
$T1
$R1
$P1
ls bt/out
cat -v bt/out/*.flo
echo "----- packet toss 3 (flo removed) -----"
rm -f bt/out/*.flo
cp tmp_out/*.pkt pin
$T1
$R1
$P1
ls bt/out
cat -v bt/out/*.flo


echo "----- DOS config -------------------------------------------------------"
echo "----- file1 -----"
$F2 $A `pwd`/tmp_file1.txt
echo "FLO file:"
cat -v bt/out/*.flo
echo "----- file2 -----"
$F2 $A '#'`pwd`/tmp_file2.txt
echo "FLO file:"
cat -v bt/out/*.flo
echo "----- file3 -----"
$F2 $A '^'`pwd`/tmp_file3.txt
echo "FLO file:"
cat -v bt/out/*.flo

echo "----- file1 again -----"
$F2 $A '#'`pwd`/tmp_file1.txt
echo "FLO file:"
cat -v bt/out/*.flo
echo "----- file2 again -----"
$F2 $A '^'`pwd`/tmp_file2.txt
echo "FLO file:"
cat -v bt/out/*.flo
echo "----- file3 again -----"
$F2 $A `pwd`/tmp_file3.txt
echo "FLO file:"
cat -v bt/out/*.flo

