#!/bin/sh

../tr.init

T="../../src/gate/rfc2ftn -c../cf/fidogate.conf -vvvvv"

echo "tc: running"
for f in articles/*/[0-9]*; do
#for f in articles/nak/8405; do
  echo ""
  echo "---------- News article file $f ----------"
  $T -n <$f
done

../../src/util/pktdebug -t outpkt/*/*.pkt
