#!/bin/sh

../tr.init

R="../../src/gate/rfc2ftn -c../cf/gate.conf -vvv"
F="../../src/gate/ftn2rfc -c../cf/gate.conf -vvv"

echo "tc: running"

# Generate EchoMail
$R -n <<EOF
Subject: Test Gateway
From: Test User <test@blah.org>
Newsgroups: test

TEST
EOF

# Move to SPOOLDIR/in and run ftn2rfc
mv outpkt/*/*.pkt pin
$F

# Run rfc2ftn on output
for f in outrfc/news/*.rfc; do
    $R -n <$f && rm -f $f;
done

# Move to SPOOLDIR/in and run ftn2rfc
mv outpkt/*/*.pkt pin
$F
