#!/bin/sh

../tr.init

T="../../src/gate/rfc2ftn -c../cf/fidogate.conf -vvvvvvvvv"

echo "tc: running"
for f in ../ti.news-a/[0-9]*; do
  echo ""
  echo "---------- News article file $f ----------"
  $T -n <$f 2>&1 | grep '^body'
done
