#!/bin/sh

../tr.init

G="../../src/gate/rfc2ftn -vv -c./config -i"

T="../../src/toss/ftntoss  -c../cf/fidogate.conf -vv -r./routing"
R="../../src/toss/ftnroute -c../cf/fidogate.conf -vv -r./routing"
P="../../src/toss/ftnpack  -c../cf/fidogate.conf -v"

echo "tc: running"

# Generate mail
echo "Test mail -> 2:2499/1.2 CRASH"
$G -a2:2452/110 -u2:2499/1.2 test@2:2499/1.2 <<EOF
Subject: Test CRASH
From: test_user@f110.n2452.z2.fidonet.org
X-Flags: mnc

TEST CRASH
EOF

echo "Test mail -> 2:2499/1.2 NORMAL"
$G -a2:2452/110 -u2:2499/1.2 test@2:2499/1.2 <<EOF
Subject: Test NORMAL
From: test_user@f110.n2452.z2.fidonet.org
X-Flags: mn

TEST NORMAL
EOF

echo "Test mail -> 2:2499/1.2 HOLD"
$G -a2:2452/110 -u2:2499/1.2 test@2:2499/1.2 <<EOF
Subject: Test HOLD
From: test_user@f110.n2452.z2.fidonet.org
X-Flags: mnh

TEST HOLD
EOF


# Move to SPOOLDIR/toss/in and run ftntoss/ftnroute
mv outpkt/mail/*.pkt pin
$T
$R
$P


# Generate mail
echo "Test mail -> 2:2471/241 NORMAL"
$G -a2:2452/110 -u2:2471/2415 test2471@2:2471/2415 <<EOF
Subject: Test 2:2471/2415
From: test_user@f110.n2452.z2.fidonet.org
X-Flags: mn

TEST CRASH
EOF

# Move to SPOOLDIR/toss/in and run ftntoss/ftnroute
mv outpkt/mail/*.pkt pin
$T
$R
$P


