/* Automatically generated by subst.pl --- DO NOT EDIT!!! */

/*
 * FIDOGATE
 *
 * $Id: cf_abbrev.c,v 4.6 1998/02/25 09:15:25 mj Exp $
 */

{ 'B', cf_p_btbasedir },
{ 'G', cf_p_logdir },
{ 'C', cf_p_configdir },
{ 'L', cf_p_libdir },
{ 'N', cf_p_bindir },
{ 'V', cf_p_vardir },
{ 'K', cf_p_lockdir },
{ 'U', cf_p_uuinbound },
{ 'S', cf_p_spooldir },
{ 'P', cf_p_pinbound },
{ 'I', cf_p_inbound },
