/* Automatically generated by subst.pl --- DO NOT EDIT!!! */

/*
 * FIDOGATE
 *
 * $Id: cf_abbrev.c,v 4.18 2001/10/21 20:17:22 mj Exp $
 */

{ 'I', cf_p_inbound },
{ 'S', cf_p_spooldir },
{ 'K', cf_p_lockdir },
{ 'U', cf_p_uuinbound },
{ 'P', cf_p_pinbound },
{ 'L', cf_p_libdir },
{ 'B', cf_p_btbasedir },
{ 'G', cf_p_logdir },
{ 'N', cf_p_bindir },
{ 'C', cf_p_configdir },
{ 'V', cf_p_vardir },
