/* Automatically generated by subst.pl --- DO NOT EDIT!!! */

/*
 * FIDOGATE
 *
 * $Id: cf_funcs.c,v 4.1 1998/01/13 20:34:42 mj Exp $
 */

#include "fidogate.h"

/***** OUTBOUND *****/
static char *cf_p_s_outbound(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("OUTBOUND", TRUE)) )
	    pval = DEFAULT_OUTBOUND;
	debug(8, "config: OUTBOUND %s", pval);
    }
    return pval;
}
char *cf_p_outbound(void)
{
    return cf_p_s_outbound(NULL);
}
char *cf_s_outbound(char *s)
{
    return cf_p_s_outbound(s);
}

/***** BTBASEDIR *****/
static char *cf_p_s_btbasedir(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("BTBASEDIR", TRUE)) )
	    pval = DEFAULT_BTBASEDIR;
	debug(8, "config: BTBASEDIR %s", pval);
    }
    return pval;
}
char *cf_p_btbasedir(void)
{
    return cf_p_s_btbasedir(NULL);
}
char *cf_s_btbasedir(char *s)
{
    return cf_p_s_btbasedir(s);
}

/***** IFMAILDIR *****/
static char *cf_p_s_ifmaildir(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("IFMAILDIR", TRUE)) )
	    pval = DEFAULT_IFMAILDIR;
	debug(8, "config: IFMAILDIR %s", pval);
    }
    return pval;
}
char *cf_p_ifmaildir(void)
{
    return cf_p_s_ifmaildir(NULL);
}
char *cf_s_ifmaildir(char *s)
{
    return cf_p_s_ifmaildir(s);
}

/***** LOGDIR *****/
static char *cf_p_s_logdir(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("LOGDIR", TRUE)) )
	    pval = DEFAULT_LOGDIR;
	debug(8, "config: LOGDIR %s", pval);
    }
    return pval;
}
char *cf_p_logdir(void)
{
    return cf_p_s_logdir(NULL);
}
char *cf_s_logdir(char *s)
{
    return cf_p_s_logdir(s);
}

/***** NEWSLIBDIR *****/
static char *cf_p_s_newslibdir(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("NEWSLIBDIR", TRUE)) )
	    pval = DEFAULT_NEWSLIBDIR;
	debug(8, "config: NEWSLIBDIR %s", pval);
    }
    return pval;
}
char *cf_p_newslibdir(void)
{
    return cf_p_s_newslibdir(NULL);
}
char *cf_s_newslibdir(char *s)
{
    return cf_p_s_newslibdir(s);
}

/***** NEWSVARDIR *****/
static char *cf_p_s_newsvardir(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("NEWSVARDIR", TRUE)) )
	    pval = DEFAULT_NEWSVARDIR;
	debug(8, "config: NEWSVARDIR %s", pval);
    }
    return pval;
}
char *cf_p_newsvardir(void)
{
    return cf_p_s_newsvardir(NULL);
}
char *cf_s_newsvardir(char *s)
{
    return cf_p_s_newsvardir(s);
}

/***** CONFIGDIR *****/
static char *cf_p_s_configdir(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("CONFIGDIR", TRUE)) )
	    pval = DEFAULT_CONFIGDIR;
	debug(8, "config: CONFIGDIR %s", pval);
    }
    return pval;
}
char *cf_p_configdir(void)
{
    return cf_p_s_configdir(NULL);
}
char *cf_s_configdir(char *s)
{
    return cf_p_s_configdir(s);
}

/***** LIBDIR *****/
static char *cf_p_s_libdir(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("LIBDIR", TRUE)) )
	    pval = DEFAULT_LIBDIR;
	debug(8, "config: LIBDIR %s", pval);
    }
    return pval;
}
char *cf_p_libdir(void)
{
    return cf_p_s_libdir(NULL);
}
char *cf_s_libdir(char *s)
{
    return cf_p_s_libdir(s);
}

/***** NEWSETCDIR *****/
static char *cf_p_s_newsetcdir(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("NEWSETCDIR", TRUE)) )
	    pval = DEFAULT_NEWSETCDIR;
	debug(8, "config: NEWSETCDIR %s", pval);
    }
    return pval;
}
char *cf_p_newsetcdir(void)
{
    return cf_p_s_newsetcdir(NULL);
}
char *cf_s_newsetcdir(char *s)
{
    return cf_p_s_newsetcdir(s);
}

/***** BINDIR *****/
static char *cf_p_s_bindir(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("BINDIR", TRUE)) )
	    pval = DEFAULT_BINDIR;
	debug(8, "config: BINDIR %s", pval);
    }
    return pval;
}
char *cf_p_bindir(void)
{
    return cf_p_s_bindir(NULL);
}
char *cf_s_bindir(char *s)
{
    return cf_p_s_bindir(s);
}

/***** VARDIR *****/
static char *cf_p_s_vardir(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("VARDIR", TRUE)) )
	    pval = DEFAULT_VARDIR;
	debug(8, "config: VARDIR %s", pval);
    }
    return pval;
}
char *cf_p_vardir(void)
{
    return cf_p_s_vardir(NULL);
}
char *cf_s_vardir(char *s)
{
    return cf_p_s_vardir(s);
}

/***** LOCKDIR *****/
static char *cf_p_s_lockdir(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("LOCKDIR", TRUE)) )
	    pval = DEFAULT_LOCKDIR;
	debug(8, "config: LOCKDIR %s", pval);
    }
    return pval;
}
char *cf_p_lockdir(void)
{
    return cf_p_s_lockdir(NULL);
}
char *cf_s_lockdir(char *s)
{
    return cf_p_s_lockdir(s);
}

/***** NEWSSPOOLDIR *****/
static char *cf_p_s_newsspooldir(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("NEWSSPOOLDIR", TRUE)) )
	    pval = DEFAULT_NEWSSPOOLDIR;
	debug(8, "config: NEWSSPOOLDIR %s", pval);
    }
    return pval;
}
char *cf_p_newsspooldir(void)
{
    return cf_p_s_newsspooldir(NULL);
}
char *cf_s_newsspooldir(char *s)
{
    return cf_p_s_newsspooldir(s);
}

/***** FTPINBOUND *****/
static char *cf_p_s_ftpinbound(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("FTPINBOUND", TRUE)) )
	    pval = DEFAULT_FTPINBOUND;
	debug(8, "config: FTPINBOUND %s", pval);
    }
    return pval;
}
char *cf_p_ftpinbound(void)
{
    return cf_p_s_ftpinbound(NULL);
}
char *cf_s_ftpinbound(char *s)
{
    return cf_p_s_ftpinbound(s);
}

/***** UUINBOUND *****/
static char *cf_p_s_uuinbound(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("UUINBOUND", TRUE)) )
	    pval = DEFAULT_UUINBOUND;
	debug(8, "config: UUINBOUND %s", pval);
    }
    return pval;
}
char *cf_p_uuinbound(void)
{
    return cf_p_s_uuinbound(NULL);
}
char *cf_s_uuinbound(char *s)
{
    return cf_p_s_uuinbound(s);
}

/***** SPOOLDIR *****/
static char *cf_p_s_spooldir(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("SPOOLDIR", TRUE)) )
	    pval = DEFAULT_SPOOLDIR;
	debug(8, "config: SPOOLDIR %s", pval);
    }
    return pval;
}
char *cf_p_spooldir(void)
{
    return cf_p_s_spooldir(NULL);
}
char *cf_s_spooldir(char *s)
{
    return cf_p_s_spooldir(s);
}

/***** PINBOUND *****/
static char *cf_p_s_pinbound(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("PINBOUND", TRUE)) )
	    pval = DEFAULT_PINBOUND;
	debug(8, "config: PINBOUND %s", pval);
    }
    return pval;
}
char *cf_p_pinbound(void)
{
    return cf_p_s_pinbound(NULL);
}
char *cf_s_pinbound(char *s)
{
    return cf_p_s_pinbound(s);
}

/***** INBOUND *****/
static char *cf_p_s_inbound(char *s)
{
    static char *pval = NULL;
    if(s)
        pval = strsave(s);
    if(! pval)
    {
	if( ! (pval = cf_get_string("INBOUND", TRUE)) )
	    pval = DEFAULT_INBOUND;
	debug(8, "config: INBOUND %s", pval);
    }
    return pval;
}
char *cf_p_inbound(void)
{
    return cf_p_s_inbound(NULL);
}
char *cf_s_inbound(char *s)
{
    return cf_p_s_inbound(s);
}

