/* Automatically generated by subst.pl --- DO NOT EDIT!!! */

/*
 * FIDOGATE
 *
 * $Id: cf_funcs.h,v 4.1 1998/01/13 20:33:52 mj Exp $
 */

char *cf_p_outbound(void);
char *cf_s_outbound(char *);
char *cf_p_btbasedir(void);
char *cf_s_btbasedir(char *);
char *cf_p_ifmaildir(void);
char *cf_s_ifmaildir(char *);
char *cf_p_logdir(void);
char *cf_s_logdir(char *);
char *cf_p_newslibdir(void);
char *cf_s_newslibdir(char *);
char *cf_p_newsvardir(void);
char *cf_s_newsvardir(char *);
char *cf_p_configdir(void);
char *cf_s_configdir(char *);
char *cf_p_libdir(void);
char *cf_s_libdir(char *);
char *cf_p_newsetcdir(void);
char *cf_s_newsetcdir(char *);
char *cf_p_bindir(void);
char *cf_s_bindir(char *);
char *cf_p_vardir(void);
char *cf_s_vardir(char *);
char *cf_p_lockdir(void);
char *cf_s_lockdir(char *);
char *cf_p_newsspooldir(void);
char *cf_s_newsspooldir(char *);
char *cf_p_ftpinbound(void);
char *cf_s_ftpinbound(char *);
char *cf_p_uuinbound(void);
char *cf_s_uuinbound(char *);
char *cf_p_spooldir(void);
char *cf_s_spooldir(char *);
char *cf_p_pinbound(void);
char *cf_s_pinbound(char *);
char *cf_p_inbound(void);
char *cf_s_inbound(char *);
