/* Automatically generated by subst.pl --- DO NOT EDIT!!! */

/*
 * FIDOGATE
 *
 * $Id: paths.h,v 4.1 1998/01/13 20:33:53 mj Exp $
 */

#define OUTBOUND                        "/var/spool/bt"
#define BTBASEDIR                       "/var/spool/bt"
#define IFMAILDIR                       "/usr/local/lib/ifmail"
#define LOGDIR                          "/var/log/fidogate"
#define NEWSLIBDIR                      "/usr/lib/news"
#define NEWSVARDIR                      "/var/lib/news"
#define CONFIGDIR                       "/etc/fidogate"
#define LIBDIR                          "/usr/lib/fidogate"
#define NEWSETCDIR                      "/etc/news"
#define BINDIR                          "/usr/lib/fidogate/bin"
#define VARDIR                          "/var/lib/fidogate"
#define LOCKDIR                         "/var/lock/fidogate"
#define NEWSSPOOLDIR                    "/var/spool/news"
#define FTPINBOUND                      "/var/spool/bt/ftpin"
#define UUINBOUND                       "/var/spool/bt/uuin"
#define SPOOLDIR                        "/var/spool/fidogate"
#define PINBOUND                        "/var/spool/bt/pin"
#define INBOUND                         "/var/spool/bt/in"

#define DEFAULT_OUTBOUND                "/var/spool/bt"
#define DEFAULT_BTBASEDIR               "/var/spool/bt"
#define DEFAULT_IFMAILDIR               "/usr/local/lib/ifmail"
#define DEFAULT_LOGDIR                  "/var/log/fidogate"
#define DEFAULT_NEWSLIBDIR              "/usr/lib/news"
#define DEFAULT_NEWSVARDIR              "/var/lib/news"
#define DEFAULT_CONFIGDIR               "/etc/fidogate"
#define DEFAULT_LIBDIR                  "/usr/lib/fidogate"
#define DEFAULT_NEWSETCDIR              "/etc/news"
#define DEFAULT_BINDIR                  "/usr/lib/fidogate/bin"
#define DEFAULT_VARDIR                  "/var/lib/fidogate"
#define DEFAULT_LOCKDIR                 "/var/lock/fidogate"
#define DEFAULT_NEWSSPOOLDIR            "/var/spool/news"
#define DEFAULT_FTPINBOUND              "/var/spool/bt/ftpin"
#define DEFAULT_UUINBOUND               "/var/spool/bt/uuin"
#define DEFAULT_SPOOLDIR                "/var/spool/fidogate"
#define DEFAULT_PINBOUND                "/var/spool/bt/pin"
#define DEFAULT_INBOUND                 "/var/spool/bt/in"
