#!/bin/sh

T1="../../src/toss/ftntoss -vv -cconfig1 -a2:2452/110 -d"
T2="../../src/toss/ftntoss -vv -cconfig2 -a2:2452/110 -d"

../tr.init

echo "tc: copying input packets"
cp ../ti.pkt-toss/*.pkt pin

echo "tc: running (killing bad)"
$T2

[ -f toss/bad/bad00001.pkt ] && \
    ../../src/util/pktdebug -s toss/bad/*.pkt

echo "tc: copying input packets"
cp ../ti.pkt-toss/*.pkt pin

echo "tc: running (saving bad)"
$T1

[ -f toss/bad/bad00001.pkt ] && \
    ../../src/util/pktdebug -s toss/bad/*.pkt
